# Generated by Django 5.1.1 on 2024-10-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaijunto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrar_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
